services:
  app:
    build: app
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]

  db:
    image: postgres:16.2-alpine
    restart: always
    user: root
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: a1s2d3f4
      POSTGRES_DB: main_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080