services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080